people/main/urls.py
from django.urls import include, path
from django.views.generic import RedirectView

from . import views
from .models import Family, Food, Person

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "",
        views.people_list,
        name="people-list",
    ),
    path(
        "family/add/",
        views.ProtectedCreateView.as_view(model=Family, fields="__all__"),
        name="create-family",
    ),
    path(
        "family/update/<int:pk>",
        views.ProtectedUpdateView.as_view(model=Family, fields="__all__"),
        name="update-family",
    ),
    path(
        "person/add/",
        views.ProtectedCreateView.as_view(model=Person, fields="__all__"),
        name="create-person",
    ),
    path(
        "person/update/<int:pk>",
        views.ProtectedUpdateView.as_view(model=Person, fields="__all__"),
        name="update-person",
    ),
    path(
        "food/add/",
        views.ProtectedCreateView.as_view(model=Food, fields="__all__"),
        name="create-food",
    ),
    path(
        "food/delete/<int:pk>",
        views.ProtectedDeleteView.as_view(model=Food, success_url="/food/list"),
        name="delete-food",
    ),
    path(
        "food/list/",
        views.ProtectedListView.as_view(model=Food),
        name="list-food",
    ),
    path(
        "food/update/<int:pk>",
        views.ProtectedUpdateView.as_view(model=Food, fields="__all__"),
        name="update-food",
    ),
]

people/people/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
]

people/main/models.py
from django.db import models
from django.urls import reverse


class Family(models.Model):
    name = models.CharField(unique=True, blank=False, max_length=256)

    def get_absolute_url(self):
        return reverse("update-family", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Food(models.Model):
    name = models.CharField(unique=True, blank=False, max_length=256)

    def get_absolute_url(self):
        return reverse("update-food", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class Person(models.Model):
    family = models.ForeignKey(
        "Family", on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(blank=False, max_length=256)
    foods_liked = models.ManyToManyField(Food, blank=True, related_name="liked_by")
    foods_disliked = models.ManyToManyField(
        Food, blank=True, related_name="disliked_by"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("update-person", kwargs={"pk": self.pk})

people/main/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Family, Person


@login_required
def people_list(request):
    context = {
        "family_list": Family.objects.all(),
        "persons_without_family": Person.objects.filter(family=None),
    }
    return render(request, "main/people_list.html", context)


# Base class to inherit from when authentication is required
@method_decorator(login_required, name="dispatch")
class ProtectedView(View):
    pass


class ProtectedCreateView(ProtectedView, CreateView):
    pass


class ProtectedDeleteView(ProtectedView, DeleteView):
    pass


class ProtectedListView(ProtectedView, ListView):
    pass


class ProtectedUpdateView(ProtectedView, UpdateView):
    pass

people/main/templates/base.html
<a style="text-align: right" href="{% url 'people-list' %}">Home</a>
<a style="text-align: right" href="{% url 'logout' %}">Logout</a>
<br /><br />
{% block content %}
{% endblock content %}

people/main/templates/main/family_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url "people-list" %}">Back to people list</a>
{% endblock content %}

people/main/templates/main/food_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url "list-food" %}">Back to food list</a>
{% endblock content %}

people/main/templates/main/food_list.html
{% extends 'base.html' %}
{% block content %}

<h3>Foods</h3>
<ul>
    {% for food in food_list %}
    <li><a href="{% url 'update-food' food.id %}">{{ food.name }}</a> (<a href="{% url 'delete-food' food.id %}">delete</a>)</li>
    </li>
    {% endfor %}
</ul>

{% endblock content %}

people/main/templates/main/people_list.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'create-family' %}">Add family</a>
<a href="{% url 'create-food' %}">Add food</a>
<a href="{% url 'create-person' %}">Add person</a>

<h3>Families</h3>
<ul>
    {% for family in family_list %}
    <li><a href="{% url 'update-family' family.id %}">{{ family.name }}</a></li>
    <ul>
        {% for person in family.person_set.all %}
        <li><a href="{% url 'update-person' person.id %}">{{ person.name }}</a></li>
        {% endfor %}
    </ul>
    </li>
    {% endfor %}
</ul>

<h3>Standalone persons</h3>
<ul>
    {% for person in persons_without_family %}
    <li><a href="{% url 'update-person' person.id %}">{{ person.name }}</a></li>
    {% endfor %}
</ul>

{% endblock content %}

people/main/templates/main/person_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url "people-list" %}">Back to people list</a>
{% endblock content %}